import { StyleSheet } from "react-native";
import { temas } from "../../global/temas";

export const style = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:temas.colors.preto,
        justifyContent:'center'
    },
    scrollContent:{
        paddingBottom:40
    },
    headerRow:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'center',
        marginBottom:10
    },
    closeButton:{
        position:'absolute',
        left:20,
        backgroundColor:'#2a211b',
        borderRadius:20,
        width:36,
        height:36,
        alignItems:'center',
        justifyContent:'center',
        borderWidth:1,
        borderColor:temas.colors.laranja
    },
    closeButtonText:{
        color:temas.colors.branco,
        fontWeight:'bold',
        fontSize:16
    },
    Titletext:{
        color:temas.colors.branco,
        fontSize:32,
        fontWeight:'bold',
        alignSelf:'center',
        marginBottom:30
    },
    emptyBox:{
        backgroundColor:temas.colors.laranjatransparent,
        borderRadius:16,
        padding:16,
        width:375,
        alignSelf:'center',
        alignItems:'center',
        marginBottom:12
    },
    emptyText:{
        color:temas.colors.branco,
        fontSize:18,
        fontWeight:'bold'
    },
    emptyHint:{
        color:temas.colors.cordotexto,
        marginTop:6
    },
    workoutCard:{
        backgroundColor:temas.colors.laranjatransparent,
        borderRadius:20,
        width:375,
        alignSelf:'center',
        padding:14,
        marginBottom:10
    },
    workoutHeader:{
        marginBottom:8
    },
    workoutName:{
        color:temas.colors.branco,
        fontSize:20,
        fontWeight:'bold'
    },
    workoutMeta:{
        color:temas.colors.cordotexto,
        fontSize:14
    },
    chipsRow:{
        flexDirection:'row',
        flexWrap:'wrap',
        gap:8,
        marginVertical:8
    },
    chip:{
        backgroundColor:'#2a211b',
        borderColor:temas.colors.laranja,
        borderWidth:1,
        paddingHorizontal:10,
        paddingVertical:6,
        borderRadius:14,
        marginRight:6,
        marginBottom:6
    },
    chipText:{
        color:temas.colors.branco,
        fontWeight:'bold',
        fontSize:12
    },
    actionsRow:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginTop:8
    },
    primaryButton:{
        backgroundColor:temas.colors.laranja,
        borderRadius:14,
        paddingVertical:10,
        paddingHorizontal:16
    },
    primaryButtonText:{
        color:temas.colors.branco,
        fontWeight:'bold'
    },
    deleteButton:{
        backgroundColor:'#b70022ff',
        borderRadius:14,
        paddingVertical:10,
        paddingHorizontal:16
    },
    deleteButtonText:{
        color:temas.colors.branco,
        fontWeight:'bold'
    },
    secondaryButton:{
        backgroundColor:'#2a211b',
        borderRadius:14,
        paddingVertical:10,
        paddingHorizontal:16,
        borderWidth:1,
        borderColor:temas.colors.laranja
    },
    secondaryButtonText:{
        color:temas.colors.branco,
        fontWeight:'bold'
    },
    editSection:{
        marginTop:10
    },
    editExerciseBox:{
        backgroundColor:'#2a211b',
        borderRadius:14,
        padding:10,
        marginTop:8,
        borderWidth:1,
        borderColor:temas.colors.laranja
    },
    editExerciseTitle:{
        color:temas.colors.branco,
        fontWeight:'bold',
        marginBottom:6
    },
    setsRow:{
        flexDirection:'row',
        flexWrap:'wrap',
        gap:8
    },
    setCard:{
        backgroundColor:temas.colors.laranjatransparent,
        borderRadius:12,
        padding:10,
        width:170
    },
    setLabel:{
        color:temas.colors.branco,
        fontWeight:'bold',
        marginBottom:6
    },
    controlRow:{
        flexDirection:'row',
        justifyContent:'space-between',
        alignItems:'center',
        marginTop:4
    },
    controlText:{
        color:temas.colors.branco
    },
    smallButtonsRow:{
        flexDirection:'row',
        gap:6
    },
    smallButton:{
        backgroundColor:temas.colors.laranja,
        borderRadius:10,
        width:28,
        height:28,
        alignItems:'center',
        justifyContent:'center'
    },
    smallButtonText:{
        color:temas.colors.branco,
        fontWeight:'bold'
    },
    editActionsRow:{
        flexDirection:'row',
        justifyContent:'space-between',
        marginTop:8
    },
    cancelButton:{
        backgroundColor:'#b70022ff',
        borderRadius:14,
        paddingVertical:10,
        paddingHorizontal:16,
        alignSelf:'flex-end',
        marginTop:8
    },
    cancelButtonText:{
        color:temas.colors.branco,
        fontWeight:'bold'
    }
});
