import { StyleSheet } from "react-native";
import { temas } from "../../global/temas";

export const style = StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:temas.colors.preto,
        justifyContent:'center'
    },
    scrollContent:{
        paddingBottom:40
    },
    title:{
        color:temas.colors.branco,
        fontSize:32,
        fontWeight:'bold',
        alignSelf:'center',
        marginBottom:20
    },
    timerBox:{
        height:80,
        backgroundColor:temas.colors.laranjatransparent,
        width:260,
        justifyContent:'center',
        alignItems:'center',
        alignSelf:'center',
        borderRadius:20,
        marginBottom:12
    },
    timerText:{
        fontWeight:'bold',
        fontSize:32,
        color:temas.colors.laranja
    },
    controlsRow:{
        flexDirection:'row',
        justifyContent:'center',
        gap:12,
        marginBottom:12
    },
    primaryButton:{
        backgroundColor:temas.colors.laranja,
        paddingHorizontal:16,
        paddingVertical:12,
        borderRadius:16
    },
    primaryButtonText:{
        color:temas.colors.branco,
        fontWeight:'bold',
        fontSize:16
    },
    secondaryButton:{
        backgroundColor:'#2a211b',
        paddingHorizontal:16,
        paddingVertical:12,
        borderRadius:16,
        borderWidth:1,
        borderColor:temas.colors.laranja
    },
    secondaryButtonText:{
        color:temas.colors.branco,
        fontWeight:'bold',
        fontSize:16
    },
    exerciseBox:{
        backgroundColor:temas.colors.laranjatransparent,
        borderRadius:20,
        padding:14,
        width:375,
        alignSelf:'center',
        marginBottom:12
    },
    exerciseName:{
        color:temas.colors.branco,
        fontSize:20,
        fontWeight:'bold'
    },
    exerciseMeta:{
        color:temas.colors.cordotexto,
        marginTop:4
    },
    completeSetButton:{
        backgroundColor:'#b70022ff',
        height:60,
        borderRadius:20,
        justifyContent:'center',
        alignItems:'center',
        marginTop:12
    },
    completeSetText:{
        color:temas.colors.branco,
        fontWeight:'bold',
        fontSize:18
    },
    restBox:{
        backgroundColor:'#2a211b',
        borderRadius:16,
        paddingVertical:10,
        paddingHorizontal:12,
        marginTop:10,
        borderColor:temas.colors.laranja,
        borderWidth:1,
        alignItems:'center'
    },
    restText:{
        color:temas.colors.branco,
        fontWeight:'bold'
    },
    progressBox:{
        alignSelf:'center',
        backgroundColor:'#2a211b',
        borderRadius:16,
        paddingVertical:8,
        paddingHorizontal:12,
        borderColor:temas.colors.laranja,
        borderWidth:1,
        marginBottom:12
    },
    progressText:{
        color:temas.colors.branco,
        fontWeight:'bold'
    },
    listBox:{
        width:375,
        alignSelf:'center'
    },
    listItem:{
        backgroundColor:'#2a211b',
        borderRadius:12,
        padding:10,
        marginVertical:6
    },
    listItemActive:{
        borderColor:temas.colors.laranja,
        borderWidth:2
    },
    listItemTitle:{
        color:temas.colors.branco,
        fontWeight:'bold',
        fontSize:16
    },
    listItemMeta:{
        color:temas.colors.cordotexto,
        fontSize:14
    },
    errorText:{
        color:temas.colors.branco,
        alignSelf:'center'
    }
});

